// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_U4j7_SU_t9hpt_4Dyd4vSRNmrgoRuhY',
    appId: '1:810251320156:web:bf4b5677e2af319535df99',
    messagingSenderId: '810251320156',
    projectId: 'tobacco-awareness',
    authDomain: 'tobacco-awareness.firebaseapp.com',
    storageBucket: 'tobacco-awareness.firebasestorage.app',
    measurementId: 'G-KR5G6S2BPM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3NgxOGM9UdHJ1BIoRKcTQoXP5dpFRqpw',
    appId: '1:82683276860:android:d427933e0b74837b28dd39',
    messagingSenderId: '82683276860',
    projectId: 'tamak-506bb',
    storageBucket: 'tamak-506bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTBkdSAa3CCp_Y2l2JUy48zb40UP_VSg0',
    appId: '1:810251320156:ios:3ed609aa2a2a1ddd35df99',
    messagingSenderId: '810251320156',
    projectId: 'tobacco-awareness',
    storageBucket: 'tobacco-awareness.firebasestorage.app',
    androidClientId: '810251320156-a53ksj6r0lm3rjad498qens6jmm8fml0.apps.googleusercontent.com',
    iosClientId: '810251320156-1rhkm4oapfp85jf92df6qk2425ldno68.apps.googleusercontent.com',
    iosBundleId: 'com.example.tobaccoAwareness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTBkdSAa3CCp_Y2l2JUy48zb40UP_VSg0',
    appId: '1:810251320156:ios:3ed609aa2a2a1ddd35df99',
    messagingSenderId: '810251320156',
    projectId: 'tobacco-awareness',
    storageBucket: 'tobacco-awareness.firebasestorage.app',
    androidClientId: '810251320156-a53ksj6r0lm3rjad498qens6jmm8fml0.apps.googleusercontent.com',
    iosClientId: '810251320156-1rhkm4oapfp85jf92df6qk2425ldno68.apps.googleusercontent.com',
    iosBundleId: 'com.example.tobaccoAwareness',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_U4j7_SU_t9hpt_4Dyd4vSRNmrgoRuhY',
    appId: '1:810251320156:web:5459aaf569ae292735df99',
    messagingSenderId: '810251320156',
    projectId: 'tobacco-awareness',
    authDomain: 'tobacco-awareness.firebaseapp.com',
    storageBucket: 'tobacco-awareness.firebasestorage.app',
    measurementId: 'G-K53D5YCY0W',
  );

}